khanlab/snakebids

snakebids/app.py
template_app/config/snakebids.yml
template_app/workflow/Snakefile

- added automatically-generated --filter_{input_type} argument for custom command-line pybids filtering
- fixes to template_app

Filter arg

---

snakebids/app.py

Just adding some missing documentation to the `SnakeBidsApp` class.

Document SnakeBidsApp

---

snakebids/__init__.py
snakebids/app.py

- adds ability to use suffix as a wildcard
- exposes wildcards to CLI with --wildcards_<input_name> options (like --filter_*)

Suffix wildcards

---

snakebids/__init__.py
snakebids/app.py
snakebids/tests/test_generate_inputs.py

This PR adds exceptions to handle errors, replacing the previous behaviour of exiting the program, and allowing calling functions to handle them if desired.
This also adopts the standard `logging` module, which allows a user to configure which logging messages are shown in a standard way.

Use exceptions and logging to handle errors

---

.bumpversion.cfg
.github/workflows/bump_version.yml

- only pull requests (instead of push)
- removed tagging

update bumpversion action

---

.github/workflows/test_deploy.yml
snakebids/__init__.py

note: still need to filter input lists with exclude_participant_label in
this case, and may need to also filter when a mix of pybids and --path_*
are used..

filters by participant_label when pybids skipped

---

.flake8
.github/workflows/test_deploy.yml
.pre-commit-config.yaml
README.rst
poetry.lock
pyproject.toml
snakebids/__init__.py
snakebids/app.py
snakebids/exceptions.py
snakebids/output.py
snakebids/project_template/{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/run.{{cookiecutter._py}}
snakebids/snakemake_io.py
snakebids/tests/mock/config.py
snakebids/tests/test_app.py
snakebids/tests/test_bids.py
snakebids/tests/test_generate_inputs.py
snakebids/tests/test_output.py
snakebids/tests/test_snakemake_io.py

This PR contains the new CI flow for snakebids. It currently incorporates `black`, `pylint`, `isort`, and `flake8`, as discussed in #63. I went through all the code and refactored/reformatted to give us a clean slate for starting.
I customized a few of the linters: `flake8`, notably, needs a few tweaks to work with `black`. I also added a few exceptions to `pylint`, and set it to fully ignore `test_*` files, as it was raising way too many issues about regular practices (e.g. using pytest fixtures, using private methods). I've never used `pylint` in my own projects, so I'd love to hear if you have a better way
of addressing this problem.
I installed a task runner: [poethepoet](https://github.com/nat-n/poethepoet). I've found it to be a nice way to standardize common tasks. Basically it …

Integrate pre-commit hooks and gh-actions linting

---

poetry.lock
pyproject.toml
snakebids/core/filtering.py

- New version (0.15.0) of pybids
- New major version of black (v22)
- New major version of PyYAML (v6) *necessary* for latest snakemake
versions
- New major version of pytest (v7)

Dependency updates

---

.github/workflows/bump_version.yml
.github/workflows/deploy.yml
snakebids/project_template/cookiecutter.json
snakebids/project_template/{{cookiecutter.app_name}}/workflow/Snakefile
snakebids/tests/test_template.py

Fix a couple of issues with the template workflow that kept it from running for me. Note: It would be good to have someone test this to make sure it wasn't some issue with my local setup that now breaks the workflow for everyone else. I've also added a test to make sure a dry-run of the generated template workflow completes successfully.
~~It would also be nice to update the release drafter to update the "Snakebids Version" in the `cookiecutter.json` -- I'll try to take a look at that before we merge this.~~ Done.
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes …

Fix template workflow

---

docs/bids_app/config.rst
docs/running_snakebids/overview.md
snakebids/core/input_generation.py

Adds some documentation for pybids.
- Add docstring to _gen_bids_layout
- Update bids_app/config.rst doc for new pybids variables
- Add instructions to "Running snakebids"

Update documentation for pybids

---

.readthedocs.yml

A small change... this seems to be the correct way to format the read the docs config these days

Update readthedocs config syntax

---

snakebids/admin.py
snakebids/project_template/cookiecutter.json
snakebids/project_template/{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/run.py

Various improvements suggested in #187. I think allowing blank responses bears a bit more discussion but this handles the other three requests.

Snakebids create enhancements

---

.github/workflows/assign.yml

The previous '@v1' was returning an error.
This is an attempt at fixing...

Update auto-assign action version

---

snakebids/core/input_generation.py

Check if BidsDir exists before indexing

---

.github/workflows/test.yml

Update setup-poetry to v4

---

snakebids/core/input_generation.py

Update some outdated references to BidsInputs

---

snakebids/core/input_generation.py
snakebids/exceptions.py
snakebids/tests/test_generate_inputs.py

This is an attempt to fix #159. I implemented @pvandyken's suggestion of raising a custom error pointing at Pybids as the root problem, but when writing the test I found it a bit hard to figure out how a Snakebids user would encounter this error in the course of normal operation (maybe @akhanf could point me at an example?).
So, the test ended up looking a bit kludgey/unrealistic, but does cover the new code.

Introduce PybidsError for cryptic pybids errors

---

snakebids/core/input_generation.py

Resolves #215 similarly to how @pvandyken suggests in that issue.

Elaborate on warning for empty components

---

snakebids/core/datasets.py
snakebids/core/filtering.py
snakebids/tests/test_datasets.py
snakebids/types.py
snakebids/utils/utils.py

Here be the implementation of `BidsComponent.filter` #202. The actual method is extremely straightforward, so mostly this PR adds a bunch of new filtering tests.

`BidsComponent.filter`

---

poetry.lock
pyproject.toml

Updates pybids to use `0.16.0+` for python3.8+
Edit: Well broke the documentation build with this…

Update pybids py37, py38+ constraints

---

snakebids/core/datasets.py
snakebids/core/input_generation.py
snakebids/exceptions.py
snakebids/tests/test_datasets.py

Add DuplicateComponentError for more precision

---

snakebids/cli.py
snakebids/tests/strategies.py
snakebids/tests/test_app.py
snakebids/tests/test_cli.py

Closes #94. The tests aren't super comprehensive but definitely increase the code coverage to the point that they would have caught #287.

Test magic args

---

docs/tutorial/tutorial.md

Describe the changes implemented in this pull request. If the changes fix a bug or resolves a feature request, be sure to link the issue (and explain how the changes address the issue). Be sure to select a label describing the PR (e.g. maintenance).

fixing small virtual env activation typo in tutorial.md

---

.github/workflows/release_drafter.yml
.github/workflows/test.yml
docs/requirements.txt

Port the documentation changes from #328 into main

Port documentation changes

---

.github/auto_assign.yml

Remove myself from reviewer list

---

.github/auto_assign.yml

This just adds @Bradley-Karat, @myousif9, and @mcespedes99 to the reviewer list. I've kept the same assignments as before - assigns everyone except the author to the reviewers.

Add new reviewers

---

README.md
docs/conf.py
docs/tutorial/tutorial.md
pyproject.toml
snakebids/project_template/tests/data/dataset_description.json

Github should automatically redirect to the new URL, but updating the repository links to point to the moved URL (which should also update the metadata over on PyPI on next release).

Update URLs to new repo link

---

.github/workflows/nightly.yml
.github/workflows/test.yml

Update khanlab/actions integration

---

snakebids/paths/_factory.py
snakebids/tests/test_paths/test_bids.py

Found a bug in the bids generator 😱. A simple enough fix.

Eliminate initial "_" when suffix is only entity

---

.github/auto_assign.yml

Update reviewer list

---

snakebids/project_template/copier.yaml

Update maximum python version in template

---

.github/workflows/upload_coverage.yml

Missed this in the previous commit

Add name to upload_coverage

---

.github/workflows/upload_coverage.yml

Attempt to only download the coverage related artefacts to fix download issues

Add pattern to coverage upload action

---

.github/workflows/test.yml
.github/workflows/upload_coverage.yml

Another attempt to fix the codecov situation.

Do codecov upload with tests and delay notifcation
