khanlab/snakebids

- .readthedocs.yml
I think autodoc is failing on readthedocs because the Snakebids' external dependencies aren't being installed -- I think this small configuration change should resolve that (I don't know if there's a good way to test it without pulling the change first, though).
> Get readthedocs to install this package for autodoc

- snakebids/__init__.py
- snakebids/app.py
- snakebids/snakemake_io.py
I ran the the Python files in the project through pylint and flake8 as the start of a refactor to identify any style issues and bring the code in line with PEP 8. This PR is almost entirely adjusting small formatting issues or making minor one-line adjustments to reflect best practices (things like changing `var == None` to `var is None`). There are a few places remaining where pylint wants function complexity to be reduced, but I'll address those in a separate PR.
On a related note, it might be worthwhile to adopt a tool like [black](https://github.com/psf/black) or [autopep8](https://github.com/hhatto/autopep8) to automatically apply these kinds of formatting changes. An example of a GitHub action that automatically formats incoming PRs is …
> Reformat to satisfy trivial requirements of pylint and flake8

- .github/workflows/black.yml
- docs/conf.py
- setup.py
- snakebids/__init__.py
- snakebids/app.py
- snakebids/snakemake_io.py
- snakebids/tests/test_bids.py
- snakebids/tests/test_generate_inputs.py
- snakebids/tests/test_snakemake_io.py
Adopting a code formatter ensures that code style is consistent across a project. Here, I've used [Black](https://github.com/psf/black) with the argument `-l 79` to bring all the Snakebids code to a style consistent with PEP 8.
This PR also adds a GitHub action that lints incoming PRs with black, to ensure that the incoming code is also formatted according to that style.
> Run black -l 79 on project, and add GH action to lint with black

- snakebids/app.py
this is probably a bug I introduced when I was playing around with different argparse set-ups, but was causing a failure once you get past the usage
> fix: was using a non-existant help_snakemake arg

- snakebids/__init__.py
Pylint complained about the complexity of a few of the functions in `__init__.py`. This PR resolves those complaints, mostly by splitting out some functionality into smaller helper functions.
> Reduce complexity of top-level script

- snakebids/tests/test_generate_inputs.py
This just adds a small test to the suffix-as-wildcard functionality in #25, which I think will be in good shape to merge once a test is added.
> Test suffix as wildcard

- snakebids/app.py
added --help_snakemake instead, to simplify the default usage and to fix the issue where [targets] from snakemake would appear before the required snakebids arguments in the combined usage.
Note that we now lose the functionality of checking whether any
namespace conflicts exist between snakebids and snakemake arguments, so will be up to the workflow author to ensure that is the case.
> removed snakemake usage from help

- snakebids/__init__.py
for `keep_indices` variable, using set() was leading to issues with ordering in hippunfold (https://github.com/khanlab/hippunfold/issues/48)
Changing to a list should fix it
Closes #41
> changed set to list to preserve ordering

- .github/workflows/bump_version.yml
using personal access token instead of github_token should allow bumpversion push to trigger another workflow
> fix bumpversion workflow

- .github/workflows/test_deploy.yml
- .gitignore
- docs/tutorial/tutorial.rst
- setup.py
- snakebids/app.py
- snakebids/tests/mock/config.py
- snakebids/tests/mock/config.yaml
- snakebids/tests/test_app.py
Currently, when supplying arguments to the command line executable (e.g. `run.py`), the `input` and `output` positional arguments are resolved (e.g. `./data` becomes `/home/user/folder/data`) and a new `config.yaml` is generated in the output folder. All keyword arguments (e.g. `--keyword argument`) are printed into the new `config.yaml` as `keyword: argument`. Snakemake is then run using the new config file as config and using the output dir as the working directory. The equivalent snakemake call would be 
```
snakemake --configfile /path/to/output/dir/config/config.yaml --directory /path/to/output/dir
```
Because the working directory is switched, any additional relative paths supplied to the original `run.py` call will now be interpreted relative to the output directory. For instance, …
> Resolve arguments annotated with type: Path 

- snakebids/__init__.py
- snakebids/tests/test_bids.py
Previously, `bids()` only accepted `str`. This extends it to allow `pathlib.Path`s.
I also refactored the `os.path.join()` calls `__init__.py` to use pathlib.
> Accepts pathlib.Path as root in bids function

- setup.py
upgrades to pybids 0.13.2. Doesn't seem to break anything as far as I can tell, and updates the bids entities etc..
> upgrade pybids version

- snakebids/tests/test_generate_inputs.py
Tests were still randomly failing with random subject ordering.  Adds some fixes to the tests to allow this to pass. 
Would be nice to remove this randomness at some point, but will leave it for another day..
> fixes to tests to allow random subject order

- docs/requirements.txt
- snakebids/project_template/{{cookiecutter.app_name}}/docs/requirements.txt
should fix failed readthedocs builds
> pin docutils<0.18 for docs

- poetry.lock
- pyproject.toml
- snakebids/__init__.py
- snakebids/app.py
- snakebids/exceptions.py
- snakebids/output.py
- snakebids/project_template/cookiecutter.json
- snakebids/project_template/{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/workflow/Snakefile
- snakebids/tests/test_app.py
- snakebids/tests/test_generate_inputs.py
- snakebids/tests/test_output.py
With this PR, snakebids will, by default, produce output in bidsapp mode, meaning snakemake results will be placed directly in the output folder. The user, via command line flag `--workflow-mode` or `-w`, can change the output to "workflow mode" which will cause the entire snakebids app to be copied to the output dir. Snakemake results will be put into the `output/results` folder.
Currently, snakebids produces output in roughly a bidsapp fashion, but still produces a `config/config.yml` file in the output directory. There is no convenient way to use the `run.py` function in a manner analogous to snakemake, that is, to run a pipeline progressively and iteratively, collecting the outputs in the results folder. At the same time, it doesn't particularly conform to bidsapp specs either, with …
> Implement workflow and bidsapp mode

- snakebids/app.py
- snakebids/tests/test_app.py
This is a quick one addressing #66. The commit msg explains it well:
The config file in bidsapp mode was stored in the `code` directory in the output folder. This introduced a breaking change, as `Snakefiles` would need to refer to the config file via `workflow.source_path()`.  This adjusts the path to match that of the parent app: `parent/config/snakebids.yml` -> `output/config/snakebids.yml`
This way, 0.4.0 will not be breaking.
See #66
> Match path of config in bidsapp mode to parent

- .github/workflows/test_deploy.yml
- pyproject.toml
Adds Python 3.10.x as a test condition and ups the python version restriction in the pyproject
> Add test support for python 3.10.

- setup.py
- snakebids/fix_dd.py
- snakebids/project_template/{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/pipeline_description.json
- snakebids/tests/data/fmriprep_deriv/dataset_description.json
Pybids is still a bit behind when it comes to parsing BIDS derivatives datasets, since the new BIDS spec (that e.g. fmriprep uses) uses a `GeneratedBy` list in the dataset_description.json, which supercedes the older `PIpelineDescription.Name` used by Pybids to parse a dataset. 
This PR adds a tool to add in a PipelineDescription to an existing dataset_description file, using the first entry of the GeneratedBy list to get the name and version. This is so we can more easily use BIDS derivatives in snakebids. Once Pybids is fixed to deal with this properly, we can ditch this, but it solves the problem for now. 
I've also added the PIpelineDescription field to our template project files, so that nakebids outputs are also compatible with pybids/snakebids when parsing as a derivative.
> Fixes for pybids dataset_description.json compatibility

- docs/running_snakebids/overview.rst
Here's the documentation for the output modes. It right now takes Bidsapp mode for granted, and introduces workflow mode as a way of directly calling the Snakemake CLI. It also teaches users to directly create or clone the app to the directory they want their results to go, and only mentions the `-W` flag at the end.
Need to make sure the file tree structures render correctly on Readthedocs. Does anyone know how to test that?
Will parts of the documentation (especially the tutorial) need to be updated to reflect new assumptions made in Snakebids app development (e.g. what kind of output to expect in Bidsapp mode)?
> Update documentation for output modes

- .bumpversion.cfg
- .github/release-drafter.yml
- .github/workflows/bump_version.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
- project_template/cookiecutter.json
- pyproject.toml
This PR (based on `0.4.0`) starts to incorporate the `release-drafter` into the github actions workflow. This adds the following functionality. 
The labels (if missing or there are others we wish to include) still need to be added to the repo.
Resolves #72. Note, the `release-drafter` won't actually start to work until it is merged into `main` and will cause the CI for this branch to fail until merged.
> Setup release drafter

- snakebids/app.py
- snakebids/tests/mock/config.py
- snakebids/tests/mock/config.yaml
- snakebids/tests/test_app.py
Previously all args were in the form --argument_one. This allows the dash to be used in place of an underscore. This has no effect on what will be printed into the config file, as all dashes (-) are converted to underscores (_) internally.
@akhanf, it would be good to update the arg in #58 to match if this goes through.
Resolves #10
> Add --dash-syntax as alias to all CLI args

- .github/workflows/bump_version.yml
- .github/workflows/release_drafter.yml
Sets up a separate workflow requiring a manual trigger to update the `release-drafter` changes.
This is intended to allow for a user to trigger an update to the CHANGELOG without rerunning the `bump` workflow that will cause a version bump. Also took advantage to add a conditional to the `bump` workflow so that if a PR is labelled with `skip_changelog` the workflow does not actually run and cause a version bump.
> Add release-drafter trigger

- .github/workflows/bump_version.yml
- .github/workflows/release_drafter.yml
Quick patch to rename the release-drafter workflow. Missed the fact it was named the same as `bump_version` workflow. 
Also uses this PR to fix the `pr-label-checker` action that was using the wrong tag.
> Rename release-drafter workflow 

- snakebids/app.py
I believe #105 was a simple as using set() for de-duplication. #akhanf, could you do me a favor and test this PR? I don't have test cases prepared, and if I made them now, they'd have to immediately be changed to accomadate the refactoring in #93.
Addresses #105
> Use set() to remove duplicate arg labels

- poetry.lock
- pyproject.toml
- snakebids/app.py
- snakebids/bids.py
- snakebids/cli.py
- snakebids/tests/mock/config.py
- snakebids/tests/test_app.py
- snakebids/tests/test_cli.py
- snakebids/utils/output.py
Here's my promised refactor (resolving issue #81). I moved stuff around quite a bit, so sorry if the diff is a bit hard to follow.
Basically, I separated logic concerns between the argparse CLI functionality, which is now stored in `cli.py`, and the actual `Snakebids` stuff: parsing the `snakemake_dir`, reading the config file, running the app. `SnakeBidsApp` now uses the excellent [`attrs`](https://www.attrs.org/en/stable/) library for initialization.  Most of the attributes (e.g. `configfile_path`, `snakefile_path`, `config`) are determined relative to the user provided `snakemake_dir`. Previously, these were calculated within the `__init__()` function, but now are determined using `attr.Factory`, which basically lets you use a function to set a default value for an attribute. The big …
> Refactor app.py

- .github/workflows/bump_version.yml
- .github/workflows/deploy.yml
Adding this into the workflow for completeness. Do we have a template that we draw from or are existing workflows currently just copying it from this repository?
Anyways, this just adds in the case for a repo to initialize release drafter if no previous tag is found (i.e. `v0.1.0`). It checks to see if `release-drafter` found a previous version, and if not, "manually" sets it to 0.1.0. The draft changelogs will still have the "Draft" title until published. 
On the deploy side, a similar check is performed, and when it reaches the publish step, it forces the tag and name of the release-drafter (this will match the `$RESOLVED_VERSION`)
It also removes the label checker, which wasn't working as intended.
Will make a separate PR to the `funcmasker-flex` repo with these changes.
> Include v0.1.0 case for release-drafter

- snakebids/bids.py
- snakebids/tests/test_bids.py
The process of working on #100 led to a lot of changes, not all of which are related. I thus thought it might be easier if I release the changes across a few PRs based on content theme. 
The main goal here was for bids() to return Paths rather than strings. Snakemake can consume Paths as input/outputs just fine, and Paths are just more convenient. 
Along the way, I refactored a few things:
- Form filename and folder in a "one-liner" list creation, rather than gradually appending items. This makes the code much more concise and clear.
- Add type annotations
> Refactor bids() function

- snakebids/core/bids.py
- snakebids/tests/test_bids.py
Hotfix for #119
Returning a Path was causing all sorts of unpredictable errors within Snakemake workflows, apparently due to lack of full Path compatibility in Snakemake
> Bids returns str instead of Path

- pyproject.toml
A small one here: this updates the `test` command in `poe` to run the entire pytest command as in gh-actions, especially including the `doctest-modules`.
> Make `poe test` run full test suite (as in gh-actions)

- snakebids/app.py
Closes #113 
Fixes bug where configfile was being incorrectly updated, was occurring because configfile was incorrectly being made an absolute path.
> Fix relative path bug in configfile

- snakebids/core/filtering.py
- snakebids/core/input_generation.py
- snakebids/tests/test_filtering.py
- snakebids/tests/test_utils.py
- snakebids/utils/utils.py
The zip list filter previously could only filter one entity-value at a time. In other words, you could search for a single subject, a single aquisition, etc, but not subjects 4 and 5 in the AP direction. This PR updates it to support any arbitrary combination of entities. It also supports regex_search, using the same interface as `pybids.get()`. A formal test was created by copying out the doc string (which admittedly doesn't add much but it's easier for me to run the test in VS-code that way). I added a new condition to the formal test to test searching by entity combinations.
Due to my use of `zip()` within `filter_list`, each `zip_list` is now returned as a tuple instead of a list. I didn't feel the need to correct this: realistically the user should not be `append()`ing anything to …
> Improve filter_list

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR just adds some default templates to collect information from users when trying to make a PR / issue. Feel free to suggest any changes or inclusions to the template.
> Add templates for issues and PRs

- .github/workflows/bump_version.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
This PR updates the workflows so protected branches can be used: 
- Switches push action to use `CasperWA/push-protected@v2` with PAT token
- Changes `bump_version.yml` trigger from `push` to `pull_request`. Only runs if this is triggered due a merged PR. Functionally the same as before.
- Added specific branches to `test.yml` to disable duplicate testing triggered by protected push.
- Runs on all branches except those that start with `push-action/`, which is a branch created by the `CasperWA/push-protect` action.
@akhanf This should allow for branch protections to be re-enabled! Will need to generate a personal access token (saved as `BP_PAT_TOKEN` in the repository secrets) with repo access for the `push-protect` to work.
> Update workflows for branch protection

- .github/workflows/assign.yml
- .github/workflows/test.yml
Resolves #131. 
Actions that require write permissions to the repo (e.g. committing and pushing during the action) or repo secrets (e.g. the use of `secrets.GITHUB_TOKEN`) does not work on forks. When `pull_request` is the trigger, the workflow only has **read access** and **if user (without write access)** authored a PR from a fork, any workflows requiring repository secrets or write access will fail. The workaround is to use `pull_request_target`, which functionally is the same as `pull_request`, but also enables **all** users to have **write access** and access to repository secrets through the workflow. 
The changes from this PR:
* Splits up reviewer assignment from test workflow for security purposes
* `pull_request_target` has some security vulnerabilities when paired with the …
> Fix auto-assign

- .github/workflows/assign.yml
Resolves #148. Changes such that the reviewer assignment will trigger only if there was no assignee to the pull request. If a PR needs to be reviewed again (due to changes), users will have to manually request.
> Change review assignment action (no automated follow-up review request)

- .github/release-drafter.yml
- README.md
Inspired by the [`pybids`](https://github.com/bids-standard/pybids/releases/tag/0.14.0) releases, this adds a badge for the latest associated zenodo object to both the release-drafter and readme. 
One thing I am unsure of with this PR is with future releases. Zenodo issues a new doi for each new release that is linked to the original ("concept") doi. Currently the badge is always grabbing the "latest" version, so I'm not sure if on a new release, any existing badges get updated. There might be a way to search for the matching version, but I haven't found an easy way for that yet.
All PRs will undergo the unit testing before being …
> Zenodo badge

- docs/bids_app/config.rst
- snakebids/app.py
- snakebids/cli.py
- snakebids/core/input_generation.py
- snakebids/project_template/{{cookiecutter.app_name}}/config/snakebids.yml
- snakebids/project_template/{{cookiecutter.app_name}}/workflow/Snakefile
- snakebids/tests/mock/config.yaml
- snakebids/tests/test_app.py
- snakebids/tests/test_generate_inputs.py
This PR adds in functionality to save the `pybids` db. 
It adds a `pybids_db` to the config, where it stores the db directory, and a flag as to whether the db should be overwritten. Wanted this to be separate from the `pybids_inputs`. This also updates the `generate_input.py` to make use of these config options. If the directory is left blank (e.g. `''`), the database will be set to `None` (if left as `''`, it saves the db in the current working directory). Also added in a few small test cases to make sure the db is working as expected.
~@pvandyken I didn't end up using the `pytest.fixtures` and `tmpdir` (mentioned last week) to create the new temporary data during testing - looked as if these temp files would be created at the beginning of the test which would have been picked up by …
> Add ability to use pybids db

- poetry.lock
- snakebids/core/filtering.py
- snakebids/core/input_generation.py
- snakebids/tests/test_generate_inputs.py
As it turns out, we had already updated pybids to `v0.15` at some point, so here I just did automatic updating of all the other deps and removed the extra code needed in pybids `v0.14`
> Remove backward-compatible pybids func call

- .github/release-drafter.yml
- .github/workflows/bump_version.yml
- .github/workflows/deploy.yml
- .github/workflows/release_drafter.yml
- .github/workflows/test.yml
Alternative approach to the issue arising in #160 and first approached in #163. See #163 for further discussion.
Bump version acts on whatever "base" a PR is merged into. This should allow maintaining multiple branches at a time, should the need arise (as it did in #160).
Both deploy and manual-release-draft workflows can now be run on any branch.
> Better version bump

- snakebids/exceptions.py
Messages provided to ConfigError were not being propogated to the root Exception class, so no error message was being printed when a config error occurred. This corrects that situation
> Propogate message to super-Exception

- .flake8
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- snakebids/__init__.py
- snakebids/core/__init__.py
- snakebids/core/input_generation.py
- snakebids/tests/helpers.py
- snakebids/tests/strategies.py
- snakebids/tests/test_generate_inputs.py
- snakebids/utils/sb_itertools.py
- typings/cached_property.pyi
Split `BidsInputs` into two classes: a smaller class describing a single dataset component and containing the lists, zip_lists, wildcard dict, and path, and a wrapper class compiling them together that takes the same API as `BidsInputs`. The inner class I've called `BidsComponent` and the wrapper I've called `BidsDataset`. The alternative name for the wrapper was `BidsComponents` (pluralized), but I found it confusing from a documentation perspective, and I think `BidsDataset` is more descriptive.
This new structure cleans up the implementation details in a few ways:
1. The old internal `_BidsLists` named tuple is no longer necessary and has been removed.
2. `input_lists` and `input_wildcards` are now defined in terms of `input_zip_lists`. This will make modification of the dataset (e.g. …
> BidsInputs Refactoring

- snakebids/cli.py
- snakebids/utils/output.py
The --force-output flag had not actually been linked to the SnakebidsArgs force property, preventing running a new app in an occupied the directory. The error was also missing a comma and was getting cut short.
> Fix forced output into occupied directory

- README.md
`poetry run pytest` doesn't cover docstring test cases, and runs benchmarks that don't need to be run. The `poe` test task is a more accurate method.
> Use correct command for testing in README

- README.md
- pyproject.toml
Really simple one, just updating the `pyproject.toml` to poetry 1.2. This prevents us from using poetry 1.1, so if anyone needs to stay legacy, speak now :smiley:
> Migrate poetry syntax to poetry v1.2

- .github/workflows/assign.yml
- .github/workflows/bump_version.yml
- .github/workflows/release_drafter.yml
- .github/workflows/test.yml
- poetry.lock
- pyproject.toml
Just version changes. A few clarifications were needed on "built extensions" (pandas, numpy, scipy) to make sure poetry installs pre-built binaries (otherwise it picks old versions no longer supported for py311 but still supported for py37 and then pip tries to build them from scratch)
> Add support for python 3.11

- snakebids/core/input_generation.py
Trivial change in one of the docstrings which had the wrong return type
> Fix docstring type in _get_lists_from_bids

- snakebids/core/input_generation.py
- snakebids/resources/bids_tags.json
- snakebids/tests/conftest.py
- snakebids/tests/helpers.py
- snakebids/tests/strategies.py
- snakebids/tests/test_generate_inputs.py
- snakebids/types.py
Skip Bids Indexing when all components have `custom_paths` specified. Also add a bunch of related tests, which incidentally covers some E2E cases.
> Skip Bids Indexing when `custom_paths` specified

- snakebids/core/datasets.py
- snakebids/core/input_generation.py
- snakebids/resources/bids_tags.json
- snakebids/tests/data/custom_config_nonstandard.json
- snakebids/tests/strategies.py
- snakebids/tests/test_generate_inputs.py
- snakebids/utils/utils.py
This corrects some of the mistakes made by the previous parser: mistakes caused by overlapping entity names (space and ce), inability to have "datatype" or "extension" as entities, and paths with just suffixes.
Now use the expanded bids_tags.json file to specifically match every tag. If a tag is given that isn't found in bids_tags.json, fall back to the previous `tag-[a-zA-Z0-1]` syntax.
Implementing this ended up being a bit more challenging than I thought. I was hoping I could just use the pybids entity info already available, but we need to *replace* the matched value with a wildcard, and there's no way of doing this without riskily trying to parse the pattern from pybids. Since I'm not willing to do that, we need to encode the missing information in our own `bids_tags.json` file.
I …
> Use entity-specific parsers

- snakebids/core/datasets.py
- snakebids/core/input_generation.py
- snakebids/tests/test_datasets.py
- snakebids/utils/utils.py
BidsDataset.from_iterable was blindly converting the iterable of components passed into a dict. If any of these components had the same name, they would overlap in the dict (since the name is used as a key), and the first would be silently removed.
Fix this by checking for duplicate names.
Resolves #181
> Block components with same names in dataset init

- snakebids/core/input_generation.py
This is a minor change in an error message that says "no image found" even if the user does not use images as inputs.
It would now read: 
```python
_logger.warning("No input file found for %s", input_name)
```
> [FIX] change error message when no input found

- poetry.lock
- pyproject.toml
- snakebids/core/datasets.py
- snakebids/project_template/{{cookiecutter.app_name}}/workflow/Snakefile
- snakebids/tests/test_datasets.py
- snakebids/tests/test_generate_inputs.py
- snakebids/utils/utils.py
- typings/deprecation.pyi
Resolves #237.
This PR does not yet include any changes to the docs, as the rewrite will be a bit complicated, and I may want to incorporate the pretty printing #197 into it to ease the explanations.
I'm using the [deprecation](https://github.com/briancurtin/deprecation) library, or rather, a custom fork of it. I wanted the deprecations to be displayed prominently in the docs, and the default sphinx directive just displays it as vanilla text without any box or anything. So I modified deprecation to allow me to nest the deprecation message in a warning box. I've raised an [issue](https://github.com/briancurtin/deprecation/issues/62) there about incorporating this into the main repository.
One other note: by default, Python actually doesn't display `DeprecationWarnings`. This is to prevent …
> Add deprecation warnings to `BidsDataset` properties slated for change

- snakebids/core/construct_bids.py
- snakebids/tests/test_bids.py
- snakebids/tests/test_datasets.py
- snakebids/utils/sb_itertools.py
Calls to bids with just datatype and/or prefix are indistinguishable from calls to bids with just suffix. Pybids would parse these paths as having suffixes. Thus, we prevent this types of calls altogether
Resolves #193
> Ensure bids() is called with identifying entities

- snakebids/app.py
The target was previously at the end of the call, but then if the last user-provided snakemake argument is something that consumes arguments (such as `-q`), the target gets misinterpreted and snakemake errors.
> Move target_rule to beginning of snakemake call

- docs/bids_app/plugins.md
- snakebids/app.py
- snakebids/tests/test_app.py
Wanted to sneak this in before the release so we don't need to do a breaking change later. 
Plugins can be trivially added via the constructor, or via SnakeBidsApp.plugins.append, so the method is redundant. Documentation and tests updated to reflect change
> Remove add_plugins method from SnakeBidsApp

- snakebids/core/input_generation.py
- snakebids/tests/test_snakemake_io.py
- snakebids/utils/snakemake_io.py
This issue's been sitting in the code latent for a while. Fixing it now because I want to use `glob_wildcards()` in some tests I'm writing.
The test suite could be expanded: using the zip_list strategies we already have is extremely low hanging fruit and would greatly simplify the existing test. And we don't actually test globbing over an actual filesystem. But I wanted to spin this off as fast as possible.
> Update glob_wildcards to return ZipLists

- docs/bids_app/workflow.md
- docs/tutorial/step6/Snakefile
- docs/tutorial/step7/Snakefile
- docs/tutorial/tutorial.md
- snakebids/core/datasets.py
- snakebids/core/input_generation.py
- snakebids/project_template/{{cookiecutter.app_name}}/workflow/Snakefile
- snakebids/tests/helpers.py
- snakebids/tests/strategies.py
- snakebids/tests/test_datasets.py
- snakebids/tests/test_generate_inputs.py
I thought it was about time we made this switch.
In addition to switching the default, I'd like to deprecate manually setting `use_bids_inputs=True` to attempt to cleanse code of this line. Perhaps we can even remove it completely one day.
One thing I did that I'm not sure any more is helpful is attempt to detect people using `BidsDataset` as if it were `BidsDatasetDict`. If a key from `BidsDatasetDict` is given to `BidsDataset`, and that key is not present in the dataset as a component, an informative error message will be printed. The problem is that the legacy code that might benefit from such a warning are also probably still using the old `config.update(generate_inputs(...))` style. In this case, all the properties from `BidsDataset` will be copied from out of the dataset into the …
> Switch default of use_bids_inputs to True

- snakebids/core/input_generation.py
- snakebids/tests/helpers.py
- snakebids/tests/test_generate_inputs.py
No behaviour change, just eliminate the warnings from the test suite
Also changed the order of `generate_inputs`. The default return value needs to be first for typing to work properly
> Remove unnecessary `use_bids_inputs = True`

- poetry.lock
- pyproject.toml
- snakebids/tests/helpers.py
- snakebids/tests/test_generate_inputs.py
- snakebids/tests/test_printing.py
- snakebids/tests/test_utils.py
Now merging through the proper channels!
The underlying [issue](https://github.com/bids-standard/pybids/issues/788) does appear to be resolved, so I restricted the failing test to py37, where it's still relevant (because we can't install the latest version of pybids on py37)
> Restrict pybids bug check to python 3.7

- .github/workflows/test.yml
- snakebids/tests/conftest.py
- snakebids/tests/test_printing.py
- snakebids/tests/test_utils.py
Been having a lot of issues with flaky tests lately, entirely due to timing inconsistencies. The failing tests are not complicated, there's not particular reason for long runtimes, and it probably has more to do with the github actions runner being slow (here's another source corroborating this https://datascience.blog.wzb.eu/2022/03/04/continuous-integration-testing-with-github-actions-using-tox-and-hypothesis/). So I'd like to just disable test deadlines altogether on for PRs: playing whack-a-mole one test a time is too much work.
> Ignore deadlines for hypothesis tests on pr

- snakebids/cli.py
- snakebids/tests/test_cli.py
Resolves #287. Noticed that the `args_dict` only returned the `key` in a list instead of a dict, and originates from changes to `_resolve_path`. The `--filter_{input_type}` calls were read in correctly. I think this bug may have been introduced when we changed some of the `List` types to `Iterable`/`Sequence`. In any case this issue was resolved by changing `Iterable` to `Sequence` in `_resolve_path`.
My :brain: can't come up with a coherent explanation why this bug was happening, but I think it probably has something to do with trying to recursively resolve the "path" in the dict when the condition `isInstance(path_candidate, Iterable)` was met in the original code.
As noted in #287, we should probably add testing for this (#94?). In the meantime, it would be good to get this patched and …
> Fix `--filter_{input_type}`

- snakebids/app.py
- snakebids/cli.py
- snakebids/exceptions.py
- snakebids/tests/helpers.py
- snakebids/tests/test_app.py
- snakebids/tests/test_cli.py
- snakebids/tests/test_generate_inputs.py
- snakebids/types.py
Resolves #258. REQUIRED and NONE just set the `pybids_inputs` to `True` and `False`, respectively, and let Snakebids parse them as usual. OPTIONAL sets the relevant filter to a sentinel value that gets picked up and drops any existing filters.
> Boolean CLI filters

- docs/api/main.rst
- docs/conf.py
- docs/requirements.txt
- poetry.lock
- snakebids/__init__.py
- snakebids/core/__init__.py
- snakebids/core/datasets.py
- snakebids/core/filtering.py
- snakebids/core/input_generation.py
- snakebids/tests/conftest.py
- snakebids/tests/strategies.py
- snakebids/tests/test_datasets.py
- snakebids/tests/test_generate_inputs.py
- snakebids/tests/test_utils.py
- snakebids/types.py
- snakebids/utils/utils.py
Resolves #243.
For a play-by-play of what I did, the commits are quite detailed and fairly well organized.
For a high level overview:
`BidsComponent` is conceived of as a multi-selectable `dict` (sort of... actually right now only `__getitem__` is implemented). If a tuple of entities is selected, you get back a `BidsPartialComponent` which has a `ZipList` but no `path` or `name`. `BidsComponent` is actually just a subclass of `BidsPartialComponent`. 
If a single entity is selected from `BidsComponent` (or `BidsPartialComponent`), you get a `BidsComponentRow`. This represents a single entity and its values, and it's implemented as a `ImmutableList` (sort of a `UserTuple`). It has the `wildcards` and `entities` properties, but instead of returning dicts, they directly return the `{str}` or …
> Implement `BidsPartialComponent`

- snakebids/core/input_generation.py
- snakebids/tests/helpers.py
- snakebids/tests/strategies.py
- snakebids/tests/test_generate_inputs.py
- snakebids/types.py
Previously, we only checked if the entire filter was set to a boolean, not if one of the entries was a boolean. This fix allows us to filter datasets where an entity must either be absent or set to a specific value.
> Allow Booleans in filter lists

- poetry.lock
- pyproject.toml
Closes #319. 
Constraints on Scipy caused an error when trying to build new Snakebids apps. This commit fixes this issue by updating the constraints on the Python version from >=3.11 to >=3.8.
Also updated the poetry.lock. Had to constrain `pytest` since it also updated to `7.4.0` which was causing pyright to error out from an partially unknown type from `pytest.FixtureRequest.node.get_closest_marker`. Can look into this later on, but wanted to get the scipy stuff working first.
> Update scipy constraints for py3.8

- snakebids/tests/strategies.py
The first part of fix got pushed to main directly by accident. This is an attempt at patching a mistake I made in the first push.
> Fix mistaken comparison of BidsEntity to str sets

- snakebids/app.py
- snakebids/tests/test_app.py
Regression introduced in #296. `--pybidsdb_dir` was no longer automatically being resolved.
The resolved path was getting overwritten by the args_dict in SnakebidsArgs. This didn't happen previously because the resolved path was saved under a different name than the CLI parameter, but since resolving the names, the CLI parameter name overwrites the resolved name.
Fix by changing the order of update_config and the manual setting of the pybids path
Describe the changes implemented in this pull request. If the changes fix a bug or resolves a feature request, be sure to link the issue (and explain how the changes address the issue). Be sure to select a label describing the PR (e.g. maintenance).
Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are …
> HOTFIX Fix pybidsdb path resolution

- .readthedocs.yml
In stable builds, readthedocs is not currently fetching git tags, which we need for determining project version. So we're getting unhelpful versions at the top of our project documentation like `0.0.1.devxxx-blahblah`.
This is an attempt to fix this by adding some post_checkout steps
> Fix version fetching in readthedocs build

- .readthedocs.yml
- snakebids/app.py
- snakebids/tests/test_app.py
Ports the fixes made onto the `v0.9.x` branch into main branch. Everything here is exactly the same as in PR #325 and #326
> Port hotfixes from 0.9.x

- .github/workflows/release_drafter.yml
- .github/workflows/test.yml
- docs/requirements.txt
Updates the documentation dependencies to use sphinx 7. The furo theme is causing problems with the current `requirements.txt`, apparently due to a regression in the way in works with sphinx 6. Rather than go through the effort of raising an issue, it was easier to just update everything. Unfortunately, this does mean we'll need a new 0.9.x release just in order to have a working docs
> Update docs dependencies

- poetry.lock
- pyproject.toml
- snakebids/cli.py
- snakebids/core/datasets.py
- snakebids/core/input_generation.py
- snakebids/tests/test_generate_inputs.py
- snakebids/tests/test_paths/test_bids.py
- snakebids/types.py
- snakebids/utils/utils.py
- typings/bids/layout/layout.pyi
- typings/snakemake/io.pyi
Fix a number of type issues arising with latest pyright
Need to lock pyright to >=1.1.324 because previous versions have a false
positive bug
Some dict.get(..., {}) require laborious workarounds because the value
type of the dict is a TypedDict, which is different than a regular dict
and can't be constructed easily on the fly. The latest pyright version
uses the latest typeshed, which changed the inference rules to prevent
our previous "hack" from working. This situation will probably never
change.
Broadened the annotated types for some keyword args on functions
accepting both fixed and generic kwargs with differing types. The fixed
kwargs need to allow at least the same types as the generic args, or we
get type issues downstream. Use type validation to compensate
> Update dependencies and pyright version

- snakebids/core/filtering.py
- snakebids/tests/helpers.py
- snakebids/tests/strategies.py
- snakebids/tests/test_generate_inputs.py
- snakebids/tests/test_paths/test_bids.py
- snakebids/tests/test_utils.py
- snakebids/utils/utils.py
The original intent of the PR was to add boolean support to `filter_list` so
that we could support boolean filters with custom paths, but I relealized after
some initial refactoring that such support doesn't really make any sense. So
now the PR has just the refactors:
This simplifies the filtering operation and will allow for more flexible
control of regex vs regular filtering in the future
RegexContainer is a container containing a regex expression. Strings are
"contained" if the "re.match" the expression
Move ContainerBag from test code to utils for use in filter_list
> Refactor filter_list to use RegexContainer

- snakebids/app.py
- snakebids/core/input_generation.py
- snakebids/tests/test_app.py
- snakebids/tests/test_generate_inputs.py
- snakebids/utils/utils.py
The resolved path was getting overwritten by the args_dict in
SnakebidsArgs. This didn't happen previously because the resolved path
was saved under a different name than the CLI parameter, but since
resolving the names, the CLI parameter name overwrites the resolved
name.
Fix by changing the order of update_config and the manual setting of the
pybids path
Resolves #333
> Add deprecation mechanism to old pybidsdb vals 

- .github/workflows/test.yml
- snakebids/app.py
- snakebids/core/input_generation.py
- snakebids/tests/test_app.py
- snakebids/tests/test_generate_inputs.py
- snakebids/utils/utils.py
This is the rest of the changes from the `0.9.x` branch brought forward into `0.10.x` in preparation for release. As these changes were already reviewed in previous PRs, this shouldn't need an extensive review cycle.
> Port forward 0.9.x changes into 0.10.x

- .github/actions/build-test-container/action.yaml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
- snakebids/tests/helpers.py
Completing the Actions refactoring suggested by @tkkuehn.
@kaitj, you're welcome to take the flow and incorporate it into your centralized repository, if you wish
> Refactor install steps into resusable workflow

- docs/bids_app/config.md
- snakebids/core/datasets.py
- snakebids/core/filtering.py
- snakebids/core/input_generation.py
- snakebids/tests/helpers.py
- snakebids/tests/test_generate_inputs.py
- snakebids/types.py
--participant-filter and --exclude-participant filter have had a couple of bugs over the past few versions:
1. Both terms would apply to every single component, even components without the subject entity. These components would have all of their entries filtered out
2. Using --exclude-participant-filter would turn on regex matching mode for every single filter. This changed the meaning of the filters (e.g. allowing partial matches), leading to workflow disruption
The overhaul fixes both bugs, while improving the organization of the
input generation code.
Additionally, the documentation states the magic filter `regex_search: True` can be used to enable regex searching for a block of filters. This hasn't worked for the past few versions. Rather than fix it, the behaviour has been silently …
> Overhaul global filtering of participants

- .github/workflows/nightly.yml
Add a nightly testing action to be run once per week. This will include running all the tests, plus, it checks whether the number of tests has changed since last calculation of runtimes, and if so, recalculates the runtimes for `pytest-split` and makes a PR.
~As always with gh-actions, getting this right will involve some dart throwing, so I'll leave this in draft until everything seems to work.~
Hopefully this works. Its hard to fully replicate the behaviour of it running automatically on the main branch, but we can repair any further issues as they come I think
> Nightly Testing Suite

- .github/workflows/test.yml
- codecov.yml
- poetry.lock
- pyproject.toml
> Add test coverage

- docs/tutorial/bids
- snakebids/project_template/tests/data/sub-001
This should solve the problem of the template not being shipped with snakebids
Unfortunately, there's no easy way to test this this works. If you install the app using a project manager as editable, the old symlink wouldn't cause a problem. But when packaging into a wheel, the symlink isn't followed, so the files aren't included. My nightly idea for installing from pypi would've picked up on this, but that ends up being quite tricky to implement so I don't think it's worth it. Hopefully this doesn't come up again!
> Move example dataset from docs into template

- snakebids/project_template/{% if build_system != 'poetry' %}pyproject.toml{% endif %}.jinja
- snakebids/project_template/{% if build_system == 'poetry' %}pyproject.toml{% endif %}.jinja
The latest versions of pulp dropped a deprecated api snakemake dependended on. Newer versions of snakemake will address this, but older versions don't have an upper pin on pulp.
We cannot lower-pin the snakemake version, as we need older snakemakes to maintain support for python < 3.11.
This is not an ideal situation, as if we want the template app to work on all python versions supported by snakebids, and if we want to support all actively maintained pythons, we won't be able to drop this pin on pulp until python 3.10 is dropped, which won't be for a few years.
Probably the best is to wait until either 3.8 or 3.9 is EOL, then change the template app to require python >= 3.11 and snakemake >= 8.2. By that point, python 3.13 or 3.14 will be released, so people should have been able to get …
> Restrict pulp version in template app

- .github/workflows/nightly.yml
Rather than just run the usual test workflow with the pinned dependencies, I thought it would be more useful to test installing the project from pypi with the latest of all dependencies. So this contains the attempt to do that. The code depends on a custom branch in khanlab/actions, but if everything works here, I'll make a merge of that branch
> Add tests of pypi installation in nightly workflow

- containers/test-template/Dockerfile
- containers/test-template/test-template.sh
- docs/bids_app/config.md
- poetry.lock
- pyproject.toml
- snakebids/core/_querying.py
- snakebids/core/input_generation.py
- snakebids/tests/test_generate_inputs.py
- snakebids/tests/test_template.py
- snakebids/types.py
Filters can now take a subkey: `match` or `search`, which will change the matching method from the default direct match to a python regex method.
> Add mechanism for regex filtering

- snakebids/tests/test_generate_inputs.py
This fixes the failing test on main.
The pybids internal formatting of values as integers caused problems
> Exclude `run` from test strategy

- .github/workflows/test.yml
- scripts/update_bids.py
- snakebids/paths/_config.py
- snakebids/paths/resources/spec.0.11.0.yaml
- snakebids/paths/specs.py
- snakebids/paths/specs.pyi
- snakebids/tests/conftest.py
- snakebids/tests/test_paths/test_bids.py
- snakebids/tests/test_paths/test_specs.py
- snakebids/tests/test_yaml.py
Just a small maintenance PR before the next release. This updates the name of the 0_10_1 spec to 0_11_0 to reflect the fact that it will be released in v0.11.0. It also declares a spec in `conftest.py` to silence the numerous warnings now being thrown for the current lack of declaration.
> Update updated spec name, declare spec for tests

- .github/workflows/nightly.yml
Also attempts to remove the `Dancefile.inject` being added for some reason, possibly by the `build-docker-container` step
> Clean old tests when recalculating durations

- snakebids/core/_querying.py
- snakebids/tests/test_generate_inputs.py
Discovered via testing in another branch that pybid's regex search defaults to case-insensitive, which I find unexpected. I'd prefer it be made case-sensitive, especially for snakebids where filters will often be saved into configuration files and should be explicit. This would also simplify our test suite, as I won't have to special case the previous failure.
This uses in-pattern regex groups to disable the flag. In the future, this same technique could be used to enable more customization of flags.
Also cleans up the logic in the filter parsing functions
> Default to case-insensitive search for regex

- snakebids/core/datasets.py
- snakebids/tests/test_admin.py
- snakebids/tests/test_datasets.py
- snakebids/tests/test_generate_inputs.py
Previously returned an empty list. This is different from a component with no entries (but with wildcards), which should return an empty list
Resolves #371
> Expand paths unaltered when comp has no wcards

- snakebids/tests/test_paths/test_bids.py
A failing test drew "ce" by chance, which is a valid entity name
> Prevent custom entities from drawing standard ent

- .github/workflows/test.yml
My attempt to fix the codecoverage by doing all the code uploading in a separate job after all the testing is done. (followed the blog https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/)
> Move codecoverage upload to seperate job

- .github/workflows/assign.yml
Noticed in #362, the auto-assign action did not automatically assign reviewers when a draft was marked as "Ready for review". The default `pull_request_target` triggers are `opened`, `synchronize`, and `reopened`. This PR explicitly defines these defaults in the workflow and also adds `ready_for_review`, which will trigger the assignment when a draft has been converted.
> Update auto-assign actions workflow

- pyproject.toml
- snakebids/__init__.py
- snakebids/_warningformat.py
I find the default formatting of warnings by the python module a bit unreadable, especially given our current tendency to do multiline, complex explanations (for instance, it prints the problematic line after the warning message, which is confusing).
The warnings module does allow reassignment of the format function, and that's what I've attempted here. A screenshot is attached below. There is a bit of a problem with this though, because any other code throwing warnings would be affected, as there's only a single warning module. @kaitj, if you're not comfortable with this, we can close this, this isn't a huge deal.
> Update the warning format to be more readable

- .readthedocs.yml
Should fix the failing build in #393 
Corrected as advised [here](https://github.com/python-poetry/poetry/issues/9025)
> Correctly activate virtualenv in readthedocs build

- poetry.lock
- pyproject.toml
Older versions don't have the `alias` parameter in `attrs.field`, which is used in the repository
> Pin attrs to 22.2.0

- snakebids/core/_querying.py
- snakebids/tests/test_generate_inputs.py
The previous restriction was arbitrary. The use of both works according to the set operation:
POPULATION ∩ INCLUDE - EXCLUDE
This will allow better CLI composability.
The tests for include and exclude-participant-label have been rolled into one test.
Resolves #343
> Allow simult. use of partic incl and excl flags

- .github/actions/build-test-container/action.yaml
The action was supposed to enable caching of the docker container, but it didn't seem to be working, so I switched to the local cache method described in https://docs.docker.com/build/ci/github-actions/cache/#local-cache
> Remove reproducible-containers/buildkit-cache-dance

- docs/bids_app/config.md
- docs/migration/0.11_to_0.12.md
- docs/migration/0.5_to_0.8.md
- docs/migration/0.7_to_0.8.md
- docs/migration/index.md
- docs/running_snakebids/overview.md
- docs/tutorial/step8/config.yml
- docs/tutorial/step8/run.py
- docs/tutorial/tutorial.md
Changes the final step of the tutorial to use the new bidsapp syntax. `fwhm` is brought in a specific example for the way CLI arguments can be created.
Still sparse on details for what `bidsapp.app` actually does and how it can be used. This will come with time.
> Update tutorial for new bidsapp

- .github/workflows/nightly.yml
Old code wasn't counting doctests, and spurious warning lines were being included in the count.
> Fix test-counting code

- snakebids/app.py
- snakebids/tests/test_app.py
strings being passed to the arguments in old apps were breaking. Convert now to Paths
> Add converters to SnakeBidsApp

- snakebids/bidsapp/run.py
- snakebids/snakemake_compat.pyi
- snakebids/tests/test_bidsapp.py
This results in the Runner __repr__ being printed when using app.run as
an entrypoint
> Remove return from run method on Runner

- .github/labeler.yml
- .github/workflows/labeler.yml
Automatically label PRs based on the first part of the branch name:
```
fix/ -> bug
feat/ -> enhancement
maint/ -> maintenance
doc/ -> documentation
depr/ -> deprecation
test/ -> test
```
> Add labeller action

- .github/workflows/test.yml
- .github/workflows/upload_coverage.yml
The hope is that this will give us access to the CODECOV_TOKEN secret so that we don't hit the rate limit
> Move upload_coverage to seperate workflow

- snakebids/resources/bids_tags.json
- snakebids/tests/strategies.py
- snakebids/utils/utils.py
When used with `run`, the leading 0 gets stripped because run is converted into an int. This breaks tests that instantiate a dataset on the filesystem and re-parse it using generate_inputs. Easiest solution is to just to prevent these values entirely
> Prevent bids values with leading 0s in tests

- .github/workflows/nightly.yml
Nightly test still not properly comparing the number of tests correctly, this time due to a mistake in logic.
> Fix comparison syntax in tet counting logic

- snakebids/exceptions.py
- snakebids/plugins/__init__.py
- snakebids/plugins/__init__.pyi
- snakebids/plugins/component_edit.py
- snakebids/tests/test_plugins/test_component_edit.py
Adds :match and :search as valid filter methods, each of which should
take =VALUE.
Expands error handling to give different error messages for different
filter misspecifications.
> Allow regex from the cli

- .github/workflows/codespell.yml
- .pre-commit-config.yaml
- README.md
- docs/api/paths.rst
- docs/migration/0.11_to_0.12.md
- docs/migration/0.7_to_0.8.md
- pyproject.toml
- scripts/update_bids.py
- snakebids/app.py
- snakebids/bidsapp/hookspecs.py
- snakebids/cli.py
- snakebids/core/datasets.py
- snakebids/core/input_generation.py
- snakebids/io/printing.py
- snakebids/jinja2_ext/snakebids_version.py
- snakebids/plugins/base.py
- snakebids/plugins/bidsargs.py
- snakebids/plugins/component_edit.py
- snakebids/plugins/pybidsdb.py
- snakebids/plugins/validator.py
- snakebids/project_template/{{name_slug}}/config/snakebids.yml
- snakebids/tests/test_datasets.py
- snakebids/tests/test_generate_inputs.py
- snakebids/utils/containers.py
- snakebids/utils/output.py
- snakebids/utils/snakemake_io.py
More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.
> Add codespell support (config, workflow to detect/not fix) and make it fix few typos
